program testBadInput4;
#include( "stdlib.hhf" )

static
  input: int32;

begin testBadInput4;

  // This forever loop reports until the user enters
  // a good integer and the break statement below
  // exists the loop. Note that the break statement
  // appears in an unprotected section of the try..endtry
  // statement

  forever
    try
      stdout.put( "Enter an integer value: " );
      stdin.get( input );
      stdout.put( "The first input vlue was: ", input, nl );
    unprotected
      break;
    exception( ex.ValueOutOfRange )
      stdout.put( "The value was too large, re-enter." nl );
    exception( ex.ConversionError )
      stdout.put( "The input contained illegal characters, re-enter." nl );
    endtry;
  endfor;

  // Note that the following code is outside the loop and there
  // is no try..endtry statement protecting this code.

  stdout.put( "Enter another number: " );
  stdin.get( input );
  stdout.put( "The new number is: ", input, nl );

end testBadInput4;